name: Deployment

on:
  release:
    types:
      - created

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    permissions: write-all
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-22.04
            target: aarch64-unknown-linux-gnu
          - os: macos-13
            target: x86_64-apple-darwin
          - os: macos-14
            target: aarch64-apple-darwin
          - os: windows-2022
            target: x86_64-pc-windows-msvc
          - os: windows-2022
            target: aarch64-pc-windows-msvc
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Download and Extract DCH-Basisschrift.ttf (Windows)
        if: contains(matrix.os, 'windows')
        run: |
          Invoke-WebRequest -Uri https://www.basisschrift.ch/sites/default/files/DCH-Basisschrift.ttf.zip -OutFile DCH-Basisschrift.ttf.zip
          Expand-Archive -Path DCH-Basisschrift.ttf.zip -DestinationPath fonts
          Remove-Item DCH-Basisschrift.ttf.zip

      - name: Download and Extract DCH-Basisschrift.ttf (Linux)
        if: contains(matrix.os, 'ubuntu')
        run: |
          curl -L -o DCH-Basisschrift.ttf.zip https://www.basisschrift.ch/sites/default/files/DCH-Basisschrift.ttf.zip
          unzip DCH-Basisschrift.ttf.zip -d fonts/
          rm DCH-Basisschrift.ttf.zip

      - name: Download and Extract DCH-Basisschrift.ttf (macOS)
        if: contains(matrix.os, 'macos')
        run: |
          curl -L -o DCH-Basisschrift.ttf.zip https://www.basisschrift.ch/sites/default/files/DCH-Basisschrift.ttf.zip
          unzip DCH-Basisschrift.ttf.zip -d fonts/
          rm DCH-Basisschrift.ttf.zip


      - name: Install Dependencies (Linux)
        if: contains(matrix.os, 'ubuntu')
        run: sudo apt-get update && sudo apt-get install -y libclang-dev libgtk-3-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev libssl-dev libudev-dev && sudo apt-get install -y libasound2-dev && sudo apt-get install -y cmake && cargo install --git https://github.com/burtonageo/cargo-bundle

      - name: Install Dependencies (macOS)
        if: contains(matrix.os, 'macos')
        run: brew install cmake && cargo install --git https://github.com/burtonageo/cargo-bundle

      - name: Install Dependencies (Windows)
        if: contains(matrix.os, 'windows')
        run: cargo install --force cargo-wix && choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y

      - name: Build
        run: cargo build  --release

      - name: Build .deb Package (Linux)
        if: contains(matrix.os, 'ubuntu')
        run: cargo bundle  --release

      - name: Build .app Package (macOS)
        if: contains(matrix.os, 'macos')
        run: cargo bundle  --release

      - name: Build .msi Package (Windows)
        if: contains(matrix.os, 'windows')
        run: cargo wix -p word-nerd

      # Compress for Linux Binary
      - name: Compress Output (Linux Binary)
        if: contains(matrix.os, 'ubuntu')
        run: |
          cd target/release
          zip -r word-nerd-${{ matrix.target }}.zip word-nerd
          mv word-nerd-${{ matrix.target }}.zip $GITHUB_WORKSPACE/

      # Compress for Linux .deb Package
      - name: Compress Output (Linux .deb)
        if: contains(matrix.os, 'ubuntu')
        run: |
          cd target/release/bundle/deb
          zip word-nerd-${{ matrix.target }}.deb.zip *.deb
          mv word-nerd-${{ matrix.target }}.deb.zip $GITHUB_WORKSPACE/

      # Compress for macOS (.app Bundle)
      - name: Compress Output (macOS)
        if: contains(matrix.os, 'macos')
        run: |
          cd target/release/bundle/osx
          zip -r word-nerd-${{ matrix.target }}.app.zip Word\ Nerd.app
          mv word-nerd-${{ matrix.target }}.app.zip $GITHUB_WORKSPACE/

      # Compress for Windows (.exe)
      - name: Compress Output (Windows .exe)
        if: contains(matrix.os, 'windows')
        run: |
          Compress-Archive -Path target/release/word-nerd.exe -DestinationPath word-nerd-${{ matrix.target }}.exe.zip
          Move-Item -Path word-nerd-${{ matrix.target }}.exe.zip -Destination $env:GITHUB_WORKSPACE

      # Compress for Windows (.msi)
      - name: Compress Output (Windows .msi)
        if: contains(matrix.os, 'windows')
        run: |
          cd target/wix
          Compress-Archive -Path *.msi -DestinationPath word-nerd-${{ matrix.target }}.msi.zip
          Move-Item -Path word-nerd-${{ matrix.target }}.msi.zip -Destination $env:GITHUB_WORKSPACE

      - name: Upload .deb and executable for Linux (Ubuntu)
        if: contains(matrix.os, 'ubuntu')
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: word-nerd-${{ matrix.target }}.deb.zip
          asset_name: word-nerd-${{ matrix.target }}.deb.zip
          asset_content_type: application/zip

      - name: Upload .zip for Linux (Ubuntu executable)
        if: contains(matrix.os, 'ubuntu')
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: word-nerd-${{ matrix.target }}.zip
          asset_name: word-nerd-${{ matrix.target }}.zip
          asset_content_type: application/zip

      - name: Upload .exe for Windows
        if: contains(matrix.os, 'windows')
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: word-nerd-${{ matrix.target }}.exe.zip
          asset_name: word-nerd-${{ matrix.target }}.exe.zip
          asset_content_type: application/zip

      - name: Upload .msi for Windows
        if: contains(matrix.os, 'windows')
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: word-nerd-${{ matrix.target }}.msi.zip
          asset_name: word-nerd-${{ matrix.target }}.msi.zip
          asset_content_type: application/zip

      - name: Upload .zip for macOS
        if: contains(matrix.os, 'macos')
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: word-nerd-${{ matrix.target }}.app.zip
          asset_name: word-nerd-${{ matrix.target }}.app.zip
          asset_content_type: application/zip

      - name: Upload abc.txt
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: abc.txt
          asset_name: abc.txt
          asset_content_type: text/plain

      - name: Upload manimatter.txt
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: manimatter.txt
          asset_name: manimatter.txt
          asset_content_type: text/plain

      